# Generated by Django 4.2.11 on 2024-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('optionA', models.CharField(max_length=200, null=True)),
                ('optionB', models.CharField(max_length=200, null=True)),
                ('optionC', models.CharField(max_length=200, null=True)),
                ('optionD', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
