# Generated by Django 4.2.11 on 2024-07-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Questions', 'verbose_name_plural': 'Questions'},
        ),
    ]
